### ISSUE TITLE
not working v1.4.0-1

### ISSUE THREAD

**Issue by amethystau** [Idearum/CrossCode-IntegerScaling#2]
powershell spits out

Preparing patches...
Verifying files...
Reading file contents...
WARNING: Expected 1 match but found 0, in file '.\assets\js\game.compiled.js', for line:
     else
if(b=="pixel-size"){window.IG_GAME_SCALE=(this.values[b]||0)+1;localStorage.setItem("options.scale",window.IG_GAME_SCAL
E)}
Execution have terminated! Press Enter to close the window:

**Comment by s1sw** [comment]
Hi, I've made a PR to fix this. If you don't want to wait for it to be accepted, you can find a working patch here: https://github.com/someonesomewheredev/CrossCode-IntegerScaling

**Comment by Tenome** [comment]
> Hi, I've made a PR to fix this. If you don't want to wait for it to be accepted, you can find a working patch here: https://github.com/someonesomewheredev/CrossCode-IntegerScaling

Do you know if this works with the GOG release? I got an error while running the Powershell script.

Preparing patches...
Verifying files...
Reading file contents...
Get-Content : A parameter cannot be found that matches parameter name 'Raw'.
At C:\GOG Games\CrossCode\Install-IntegerScaling.ps1:64 char:54
+         $Patch.Content = Get-Content -Path $Patch.File -Raw <<<<
    + CategoryInfo          : InvalidArgument: (:) [Get-Content], ParameterBin
   dingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Comm
   ands.GetContentCommand

WARNING: The file was empty.
Execution have terminated! Press Enter to close the window:

**Comment by Aemony** [comment]
The code has been updated to support the latest copy of the game.

> Get-Content : A parameter cannot be found that matches parameter name 'Raw'.

@Tenome, the script requires PowerShell 3.0 (which added support for the `-Raw` parameter). Based on your error message you're running the script using PowerShell 2.0. You would need to update Windows to get PowerShell 3.0 or newer (we're like up to v5 or v7 now depending on the system).
