### ISSUE TITLE
A parameter cannot be found that matches parameter name 'Raw'

### ISSUE THREAD

**Issue by Tenome** [Idearum/CrossCode-IntegerScaling#4]
Preparing patches...
Verifying files...
Reading file contents...
Get-Content : A parameter cannot be found that matches parameter name 'Raw'.
At C:\GOG Games\CrossCode\Install-IntegerScaling.ps1:64 char:54
+         $Patch.Content = Get-Content -Path $Patch.File -Raw <<<<
    + CategoryInfo          : InvalidArgument: (:) [Get-Content], ParameterBin
   dingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Comm
   ands.GetContentCommand

WARNING: The file was empty.
Execution have terminated! Press Enter to close the window:

---

Is this an issue specific to the GOG release?

**Comment by s1sw** [comment]
What version of Windows are you using? It seems like the version of Powershell you have is missing the `-Raw` parameter.

**Comment by Aemony** [comment]
The script requires PowerShell 3.0 (which added support for the -Raw parameter). Based on your error message you're running the script using PowerShell 2.0. You would need to update Windows to get PowerShell 3.0 or newer (we're like up to v5 or v7 now depending on the system).
